"""Responses.

responses serve both testing purpose aswell as dynamic docstring replacement
"""
responses = {
    "_screener": {
        "url": "/screener/predefined/{name}",
        "response": {
            "rows": [
                {
                    "symbol": "ESPR",
                    "shortName": "Esperion Therapeutics, Inc.",
                    "longName": "Esperion Therapeutics, Inc.",
                    "quoteType": "EQUITY",
                    "currency": "USD",
                    "regularMarketPrice": {"raw": 29.39, "fmt": "29.39"},
                    "regularMarketChange": {"raw": 1.0599995, "fmt": "1.06"},
                    "regularMarketChangePercent": {"raw": 3.7416148, "fmt": "3.74%"},
                    "regularMarketVolume": {
                        "raw": 1268153,
                        "fmt": "1.268M",
                        "longFmt": "1,268,153",
                    },
                    "averageDailyVolume3Month": {
                        "raw": 842390,
                        "fmt": "842,390",
                        "longFmt": "842,390",
                    },
                    "marketCap": {
                        "raw": 821233024,
                        "fmt": "821.233M",
                        "longFmt": "821,233,024",
                    },
                    "fiftyTwoWeekLow": {"raw": 23.9, "fmt": "23.90"},
                    "fiftyTwoWeekHigh": {"raw": 53.73, "fmt": "53.73"},
                    "regularMarketOpen": {"raw": 28.21, "fmt": "28.21"},
                    "priceHint": 2,
                },
                {
                    "symbol": "CLVS",
                    "shortName": "Clovis Oncology, Inc.",
                    "longName": "Clovis Oncology, Inc.",
                    "quoteType": "EQUITY",
                    "currency": "USD",
                    "regularMarketPrice": {"raw": 7.86, "fmt": "7.86"},
                    "regularMarketChange": {"raw": 2.54, "fmt": "2.54"},
                    "regularMarketChangePercent": {"raw": 47.744358, "fmt": "47.74%"},
                    "regularMarketVolume": {
                        "raw": 331763706,
                        "fmt": "331.764M",
                        "longFmt": "331,763,706",
                    },
                    "averageDailyVolume3Month": {
                        "raw": 13614618,
                        "fmt": "13.615M",
                        "longFmt": "13,614,618",
                    },
                    "marketCap": {
                        "raw": 821605824,
                        "fmt": "821.606M",
                        "longFmt": "821,605,824",
                    },
                    "fiftyTwoWeekLow": {"raw": 3.98, "fmt": "3.98"},
                    "fiftyTwoWeekHigh": {"raw": 11.1, "fmt": "11.10"},
                    "regularMarketOpen": {"raw": 6.4, "fmt": "6.40"},
                    "priceHint": 2,
                },
                {
                    "symbol": "BLNK",
                    "shortName": "Blink Charging Co. Common Stock",
                    "longName": "Blink Charging Co.",
                    "quoteType": "EQUITY",
                    "currency": "USD",
                    "regularMarketPrice": {"raw": 38.24, "fmt": "38.24"},
                    "regularMarketChange": {"raw": 2.290001, "fmt": "2.29"},
                    "regularMarketChangePercent": {"raw": 6.3699613, "fmt": "6.37%"},
                    "regularMarketVolume": {
                        "raw": 5620010,
                        "fmt": "5.62M",
                        "longFmt": "5,620,010",
                    },
                    "averageDailyVolume3Month": {
                        "raw": 11127281,
                        "fmt": "11.127M",
                        "longFmt": "11,127,281",
                    },
                    "marketCap": {
                        "raw": 1591166464,
                        "fmt": "1.591B",
                        "longFmt": "1,591,166,464",
                    },
                    "fiftyTwoWeekLow": {"raw": 1.3, "fmt": "1.30"},
                    "fiftyTwoWeekHigh": {"raw": 64.5, "fmt": "64.50"},
                    "regularMarketOpen": {"raw": 36.13, "fmt": "36.13"},
                    "priceHint": 2,
                },
                {
                    "symbol": "SKT",
                    "shortName": "Tanger Factory Outlet Centers, ",
                    "longName": "Tanger Factory Outlet Centers, Inc.",
                    "quoteType": "EQUITY",
                    "currency": "USD",
                    "regularMarketPrice": {"raw": 16.83, "fmt": "16.83"},
                    "regularMarketChange": {"raw": -0.3600006, "fmt": "-0.36"},
                    "regularMarketChangePercent": {"raw": -2.0942445, "fmt": "-2.09%"},
                    "regularMarketVolume": {
                        "raw": 2925256,
                        "fmt": "2.925M",
                        "longFmt": "2,925,256",
                    },
                    "averageDailyVolume3Month": {
                        "raw": 5614301,
                        "fmt": "5.614M",
                        "longFmt": "5,614,301",
                    },
                    "marketCap": {
                        "raw": 1574779776,
                        "fmt": "1.575B",
                        "longFmt": "1,574,779,776",
                    },
                    "fiftyTwoWeekLow": {"raw": 4.05, "fmt": "4.05"},
                    "fiftyTwoWeekHigh": {"raw": 22.4, "fmt": "22.40"},
                    "regularMarketOpen": {"raw": 17, "fmt": "17.00"},
                    "priceHint": 2,
                },
                {
                    "symbol": "GEO",
                    "shortName": "Geo Group Inc (The) REIT",
                    "longName": "The GEO Group, Inc.",
                    "quoteType": "EQUITY",
                    "currency": "USD",
                    "regularMarketPrice": {"raw": 8.13, "fmt": "8.13"},
                    "regularMarketChange": {"raw": 0.16000032, "fmt": "0.16"},
                    "regularMarketChangePercent": {"raw": 2.0075324, "fmt": "2.01%"},
                    "regularMarketVolume": {
                        "raw": 7753531,
                        "fmt": "7.754M",
                        "longFmt": "7,753,531",
                    },
                    "averageDailyVolume3Month": {
                        "raw": 4881275,
                        "fmt": "4.881M",
                        "longFmt": "4,881,275",
                    },
                    "marketCap": {
                        "raw": 986225920,
                        "fmt": "986.226M",
                        "longFmt": "986,225,920",
                    },
                    "trailingPE": {"raw": 8.648936, "fmt": "8.65"},
                    "fiftyTwoWeekLow": {"raw": 6.7, "fmt": "6.70"},
                    "fiftyTwoWeekHigh": {"raw": 15.45, "fmt": "15.45"},
                    "regularMarketOpen": {"raw": 8.05, "fmt": "8.05"},
                    "priceHint": 2,
                },
                {
                    "symbol": "VIVE",
                    "shortName": "Viveve Medical, Inc.",
                    "longName": "Viveve Medical, Inc.",
                    "quoteType": "EQUITY",
                    "currency": "USD",
                    "regularMarketPrice": {"raw": 3.42, "fmt": "3.4200"},
                    "regularMarketChange": {"raw": -0.48000002, "fmt": "-0.4800"},
                    "regularMarketChangePercent": {"raw": -12.307693, "fmt": "-12.31%"},
                    "regularMarketVolume": {
                        "raw": 1346134,
                        "fmt": "1.346M",
                        "longFmt": "1,346,134",
                    },
                    "averageDailyVolume3Month": {
                        "raw": 2191777,
                        "fmt": "2.192M",
                        "longFmt": "2,191,777",
                    },
                    "marketCap": {
                        "raw": 35368616,
                        "fmt": "35.369M",
                        "longFmt": "35,368,616",
                    },
                    "fiftyTwoWeekLow": {"raw": 2.54, "fmt": "2.5400"},
                    "fiftyTwoWeekHigh": {"raw": 14.4, "fmt": "14.4000"},
                    "regularMarketOpen": {"raw": 3.79, "fmt": "3.7900"},
                    "priceHint": 4,
                },
                {
                    "symbol": "INO",
                    "shortName": "Inovio Pharmaceuticals, Inc.",
                    "longName": "Inovio Pharmaceuticals, Inc.",
                    "quoteType": "EQUITY",
                    "currency": "USD",
                    "regularMarketPrice": {"raw": 10.11, "fmt": "10.11"},
                    "regularMarketChange": {"raw": 0.2699995, "fmt": "0.27"},
                    "regularMarketChangePercent": {"raw": 2.7438974, "fmt": "2.74%"},
                    "regularMarketVolume": {
                        "raw": 11353412,
                        "fmt": "11.353M",
                        "longFmt": "11,353,412",
                    },
                    "averageDailyVolume3Month": {
                        "raw": 15485901,
                        "fmt": "15.486M",
                        "longFmt": "15,485,901",
                    },
                    "marketCap": {
                        "raw": 2099169536,
                        "fmt": "2.099B",
                        "longFmt": "2,099,169,536",
                    },
                    "fiftyTwoWeekLow": {"raw": 6.53, "fmt": "6.53"},
                    "fiftyTwoWeekHigh": {"raw": 33.79, "fmt": "33.79"},
                    "regularMarketOpen": {"raw": 10.04, "fmt": "10.04"},
                    "priceHint": 2,
                },
                {
                    "symbol": "MAC",
                    "shortName": "Macerich Company (The)",
                    "longName": "The Macerich Company",
                    "quoteType": "EQUITY",
                    "currency": "USD",
                    "regularMarketPrice": {"raw": 13, "fmt": "13.00"},
                    "regularMarketChange": {"raw": -0.32999992, "fmt": "-0.33"},
                    "regularMarketChangePercent": {"raw": -2.4756184, "fmt": "-2.48%"},
                    "regularMarketVolume": {
                        "raw": 10771702,
                        "fmt": "10.772M",
                        "longFmt": "10,771,702",
                    },
                    "averageDailyVolume3Month": {
                        "raw": 8939680,
                        "fmt": "8.94M",
                        "longFmt": "8,939,680",
                    },
                    "marketCap": {
                        "raw": 2011984000,
                        "fmt": "2.012B",
                        "longFmt": "2,011,984,000",
                    },
                    "fiftyTwoWeekLow": {"raw": 4.81, "fmt": "4.81"},
                    "fiftyTwoWeekHigh": {"raw": 25.99, "fmt": "25.99"},
                    "regularMarketOpen": {"raw": 13.29, "fmt": "13.29"},
                    "priceHint": 2,
                },
                {
                    "symbol": "HTZGQ",
                    "shortName": "HERTZ GLOBAL HOLDINGS INC",
                    "longName": "Hertz Global Holdings, Inc.",
                    "quoteType": "EQUITY",
                    "currency": "USD",
                    "regularMarketPrice": {"raw": 1.17, "fmt": "1.1700"},
                    "regularMarketChange": {"raw": 0.07999992, "fmt": "0.0800"},
                    "regularMarketChangePercent": {"raw": 7.3394427, "fmt": "7.34%"},
                    "regularMarketVolume": {
                        "raw": 3663758,
                        "fmt": "3.664M",
                        "longFmt": "3,663,758",
                    },
                    "averageDailyVolume3Month": {
                        "raw": 5426501,
                        "fmt": "5.427M",
                        "longFmt": "5,426,501",
                    },
                    "marketCap": {
                        "raw": 182761008,
                        "fmt": "182.761M",
                        "longFmt": "182,761,008",
                    },
                    "fiftyTwoWeekLow": {"raw": 0.4, "fmt": "0.4000"},
                    "fiftyTwoWeekHigh": {"raw": 9.04, "fmt": "9.0400"},
                    "regularMarketOpen": {"raw": 1.14, "fmt": "1.1400"},
                    "priceHint": 4,
                },
                {
                    "symbol": "WKHS",
                    "shortName": "Workhorse Group, Inc.",
                    "longName": "Workhorse Group Inc.",
                    "quoteType": "EQUITY",
                    "currency": "USD",
                    "regularMarketPrice": {"raw": 16.12, "fmt": "16.12"},
                    "regularMarketChange": {"raw": 0.7200012, "fmt": "0.72"},
                    "regularMarketChangePercent": {"raw": 4.675333, "fmt": "4.68%"},
                    "regularMarketVolume": {
                        "raw": 10435994,
                        "fmt": "10.436M",
                        "longFmt": "10,435,994",
                    },
                    "averageDailyVolume3Month": {
                        "raw": 21423000,
                        "fmt": "21.423M",
                        "longFmt": "21,423,000",
                    },
                    "marketCap": {
                        "raw": 1990916864,
                        "fmt": "1.991B",
                        "longFmt": "1,990,916,864",
                    },
                    "trailingPE": {"raw": 23.028572, "fmt": "23.03"},
                    "fiftyTwoWeekLow": {"raw": 1.5, "fmt": "1.50"},
                    "fiftyTwoWeekHigh": {"raw": 42.96, "fmt": "42.96"},
                    "regularMarketOpen": {"raw": 15.46, "fmt": "15.46"},
                    "priceHint": 2,
                },
                {
                    "symbol": "KPTI",
                    "shortName": "Karyopharm Therapeutics Inc.",
                    "longName": "Karyopharm Therapeutics Inc.",
                    "quoteType": "EQUITY",
                    "currency": "USD",
                    "regularMarketPrice": {"raw": 12.06, "fmt": "12.06"},
                    "regularMarketChange": {"raw": 0.020000458, "fmt": "0.02"},
                    "regularMarketChangePercent": {"raw": 0.16611676, "fmt": "0.17%"},
                    "regularMarketVolume": {
                        "raw": 2934156,
                        "fmt": "2.934M",
                        "longFmt": "2,934,156",
                    },
                    "averageDailyVolume3Month": {
                        "raw": 2796244,
                        "fmt": "2.796M",
                        "longFmt": "2,796,244",
                    },
                    "marketCap": {
                        "raw": 900089728,
                        "fmt": "900.09M",
                        "longFmt": "900,089,728",
                    },
                    "fiftyTwoWeekLow": {"raw": 10.57, "fmt": "10.57"},
                    "fiftyTwoWeekHigh": {"raw": 25.979, "fmt": "25.98"},
                    "regularMarketOpen": {"raw": 12.1649, "fmt": "12.16"},
                    "priceHint": 2,
                },
                {
                    "symbol": "VXRT",
                    "shortName": "Vaxart, Inc. - Common Stock",
                    "longName": "Vaxart, Inc.",
                    "quoteType": "EQUITY",
                    "currency": "USD",
                    "regularMarketPrice": {"raw": 6.88, "fmt": "6.88"},
                    "regularMarketChange": {"raw": 0.26000023, "fmt": "0.26"},
                    "regularMarketChangePercent": {"raw": 3.927496, "fmt": "3.93%"},
                    "regularMarketVolume": {
                        "raw": 6682371,
                        "fmt": "6.682M",
                        "longFmt": "6,682,371",
                    },
                    "averageDailyVolume3Month": {
                        "raw": 14987160,
                        "fmt": "14.987M",
                        "longFmt": "14,987,160",
                    },
                    "marketCap": {
                        "raw": 810236992,
                        "fmt": "810.237M",
                        "longFmt": "810,236,992",
                    },
                    "fiftyTwoWeekLow": {"raw": 1.6, "fmt": "1.60"},
                    "fiftyTwoWeekHigh": {"raw": 24.9, "fmt": "24.90"},
                    "regularMarketOpen": {"raw": 6.66, "fmt": "6.66"},
                    "priceHint": 2,
                },
                {
                    "symbol": "HRTX",
                    "shortName": "Heron Therapeutics, Inc.",
                    "longName": "Heron Therapeutics, Inc.",
                    "quoteType": "EQUITY",
                    "currency": "USD",
                    "regularMarketPrice": {"raw": 15.65, "fmt": "15.65"},
                    "regularMarketChange": {"raw": 0.029999733, "fmt": "0.03"},
                    "regularMarketChangePercent": {"raw": 0.19205976, "fmt": "0.19%"},
                    "regularMarketVolume": {
                        "raw": 2699888,
                        "fmt": "2.7M",
                        "longFmt": "2,699,888",
                    },
                    "averageDailyVolume3Month": {
                        "raw": 1026709,
                        "fmt": "1.027M",
                        "longFmt": "1,026,709",
                    },
                    "marketCap": {
                        "raw": 1430355072,
                        "fmt": "1.43B",
                        "longFmt": "1,430,355,072",
                    },
                    "fiftyTwoWeekLow": {"raw": 10.74, "fmt": "10.74"},
                    "fiftyTwoWeekHigh": {"raw": 22.4, "fmt": "22.40"},
                    "regularMarketOpen": {"raw": 15.73, "fmt": "15.73"},
                    "priceHint": 2,
                },
                {
                    "symbol": "ARCH",
                    "shortName": "Arch Resources, Inc.",
                    "longName": "Arch Resources, Inc.",
                    "quoteType": "EQUITY",
                    "currency": "USD",
                    "regularMarketPrice": {"raw": 46.54, "fmt": "46.54"},
                    "regularMarketChange": {"raw": -0.9300003, "fmt": "-0.93"},
                    "regularMarketChangePercent": {"raw": -1.9591326, "fmt": "-1.96%"},
                    "regularMarketVolume": {
                        "raw": 674780,
                        "fmt": "674,780",
                        "longFmt": "674,780",
                    },
                    "averageDailyVolume3Month": {
                        "raw": 386693,
                        "fmt": "386,693",
                        "longFmt": "386,693",
                    },
                    "marketCap": {
                        "raw": 712848512,
                        "fmt": "712.849M",
                        "longFmt": "712,848,512",
                    },
                    "fiftyTwoWeekLow": {"raw": 21.8, "fmt": "21.80"},
                    "fiftyTwoWeekHigh": {"raw": 58.88, "fmt": "58.88"},
                    "regularMarketOpen": {"raw": 47.51, "fmt": "47.51"},
                    "priceHint": 2,
                },
                {
                    "symbol": "PETS",
                    "shortName": "PetMed Express, Inc.",
                    "longName": "PetMed Express, Inc.",
                    "quoteType": "EQUITY",
                    "currency": "USD",
                    "regularMarketPrice": {"raw": 34, "fmt": "34.00"},
                    "regularMarketChange": {"raw": 0.11999893, "fmt": "0.12"},
                    "regularMarketChangePercent": {"raw": 0.35418808, "fmt": "0.35%"},
                    "regularMarketVolume": {
                        "raw": 780790,
                        "fmt": "780,790",
                        "longFmt": "780,790",
                    },
                    "averageDailyVolume3Month": {
                        "raw": 868904,
                        "fmt": "868,904",
                        "longFmt": "868,904",
                    },
                    "marketCap": {
                        "raw": 689217408,
                        "fmt": "689.217M",
                        "longFmt": "689,217,408",
                    },
                    "trailingPE": {"raw": 22.222223, "fmt": "22.22"},
                    "fiftyTwoWeekLow": {"raw": 24.8, "fmt": "24.80"},
                    "fiftyTwoWeekHigh": {"raw": 57, "fmt": "57.00"},
                    "regularMarketOpen": {"raw": 34.08, "fmt": "34.08"},
                    "priceHint": 2,
                },
                {
                    "symbol": "UNFI",
                    "shortName": "United Natural Foods, Inc.",
                    "longName": "United Natural Foods, Inc.",
                    "quoteType": "EQUITY",
                    "currency": "USD",
                    "regularMarketPrice": {"raw": 34.73, "fmt": "34.73"},
                    "regularMarketChange": {"raw": 1.6199989, "fmt": "1.62"},
                    "regularMarketChangePercent": {"raw": 4.8927784, "fmt": "4.89%"},
                    "regularMarketVolume": {
                        "raw": 1967154,
                        "fmt": "1.967M",
                        "longFmt": "1,967,154",
                    },
                    "averageDailyVolume3Month": {
                        "raw": 1583036,
                        "fmt": "1.583M",
                        "longFmt": "1,583,036",
                    },
                    "marketCap": {
                        "raw": 1955160064,
                        "fmt": "1.955B",
                        "longFmt": "1,955,160,064",
                    },
                    "trailingPE": {"raw": 9.922857, "fmt": "9.92"},
                    "fiftyTwoWeekLow": {"raw": 8.28, "fmt": "8.28"},
                    "fiftyTwoWeekHigh": {"raw": 41.37, "fmt": "41.37"},
                    "regularMarketOpen": {"raw": 33.19, "fmt": "33.19"},
                    "priceHint": 2,
                },
                {
                    "symbol": "BBBY",
                    "shortName": "Bed Bath & Beyond Inc.",
                    "longName": "Bed Bath & Beyond Inc.",
                    "quoteType": "EQUITY",
                    "currency": "USD",
                    "regularMarketPrice": {"raw": 31.58, "fmt": "31.58"},
                    "regularMarketChange": {"raw": 0.9899998, "fmt": "0.99"},
                    "regularMarketChangePercent": {"raw": 3.2363513, "fmt": "3.24%"},
                    "regularMarketVolume": {
                        "raw": 5879847,
                        "fmt": "5.88M",
                        "longFmt": "5,879,847",
                    },
                    "averageDailyVolume3Month": {
                        "raw": 13366711,
                        "fmt": "13.367M",
                        "longFmt": "13,366,711",
                    },
                    "marketCap": {
                        "raw": 3827969792,
                        "fmt": "3.828B",
                        "longFmt": "3,827,969,792",
                    },
                    "fiftyTwoWeekLow": {"raw": 3.43, "fmt": "3.43"},
                    "fiftyTwoWeekHigh": {"raw": 53.9, "fmt": "53.90"},
                    "regularMarketOpen": {"raw": 30.52, "fmt": "30.52"},
                    "priceHint": 2,
                },
                {
                    "symbol": "IRBT",
                    "shortName": "iRobot Corporation",
                    "longName": "iRobot Corporation",
                    "quoteType": "EQUITY",
                    "currency": "USD",
                    "regularMarketPrice": {"raw": 119.15, "fmt": "119.15"},
                    "regularMarketChange": {"raw": 0.6800003, "fmt": "0.68"},
                    "regularMarketChangePercent": {"raw": 0.5739852, "fmt": "0.57%"},
                    "regularMarketVolume": {
                        "raw": 966674,
                        "fmt": "966,674",
                        "longFmt": "966,674",
                    },
                    "averageDailyVolume3Month": {
                        "raw": 1122757,
                        "fmt": "1.123M",
                        "longFmt": "1,122,757",
                    },
                    "marketCap": {
                        "raw": 3359922688,
                        "fmt": "3.36B",
                        "longFmt": "3,359,922,688",
                    },
                    "trailingPE": {"raw": 23.180935, "fmt": "23.18"},
                    "fiftyTwoWeekLow": {"raw": 37.01, "fmt": "37.01"},
                    "fiftyTwoWeekHigh": {"raw": 197.4, "fmt": "197.40"},
                    "regularMarketOpen": {"raw": 118.61, "fmt": "118.61"},
                    "priceHint": 2,
                },
                {
                    "symbol": "GPRE",
                    "shortName": "Green Plains, Inc.",
                    "longName": "Green Plains Inc.",
                    "quoteType": "EQUITY",
                    "currency": "USD",
                    "regularMarketPrice": {"raw": 25.63, "fmt": "25.63"},
                    "regularMarketChange": {"raw": 0.54999924, "fmt": "0.55"},
                    "regularMarketChangePercent": {"raw": 2.1929796, "fmt": "2.19%"},
                    "regularMarketVolume": {
                        "raw": 1207272,
                        "fmt": "1.207M",
                        "longFmt": "1,207,272",
                    },
                    "averageDailyVolume3Month": {
                        "raw": 1073568,
                        "fmt": "1.074M",
                        "longFmt": "1,073,568",
                    },
                    "marketCap": {
                        "raw": 1108781952,
                        "fmt": "1.109B",
                        "longFmt": "1,108,781,952",
                    },
                    "fiftyTwoWeekLow": {"raw": 3.81, "fmt": "3.81"},
                    "fiftyTwoWeekHigh": {"raw": 28.77, "fmt": "28.77"},
                    "regularMarketOpen": {"raw": 23.81, "fmt": "23.81"},
                    "priceHint": 2,
                },
                {
                    "symbol": "GME",
                    "shortName": "GameStop Corporation",
                    "longName": "GameStop Corp.",
                    "quoteType": "EQUITY",
                    "currency": "USD",
                    "regularMarketPrice": {"raw": 202.44, "fmt": "202.44"},
                    "regularMarketChange": {"raw": 0.69000244, "fmt": "0.69"},
                    "regularMarketChangePercent": {"raw": 0.34200862, "fmt": "0.34%"},
                    "regularMarketVolume": {
                        "raw": 24677297,
                        "fmt": "24.677M",
                        "longFmt": "24,677,297",
                    },
                    "averageDailyVolume3Month": {
                        "raw": 44219059,
                        "fmt": "44.219M",
                        "longFmt": "44,219,059",
                    },
                    "marketCap": {
                        "raw": 14119582720,
                        "fmt": "14.12B",
                        "longFmt": "14,119,582,720",
                    },
                    "fiftyTwoWeekLow": {"raw": 2.57, "fmt": "2.57"},
                    "fiftyTwoWeekHigh": {"raw": 483, "fmt": "483.00"},
                    "regularMarketOpen": {"raw": 195.73, "fmt": "195.73"},
                    "priceHint": 2,
                },
                {
                    "symbol": "SRNE",
                    "shortName": "Sorrento Therapeutics, Inc.",
                    "longName": "Sorrento Therapeutics, Inc.",
                    "quoteType": "EQUITY",
                    "currency": "USD",
                    "regularMarketPrice": {"raw": 9.56, "fmt": "9.56"},
                    "regularMarketChange": {"raw": 0.11000061, "fmt": "0.11"},
                    "regularMarketChangePercent": {"raw": 1.1640277, "fmt": "1.16%"},
                    "regularMarketVolume": {
                        "raw": 14339713,
                        "fmt": "14.34M",
                        "longFmt": "14,339,713",
                    },
                    "averageDailyVolume3Month": {
                        "raw": 18243480,
                        "fmt": "18.243M",
                        "longFmt": "18,243,480",
                    },
                    "marketCap": {
                        "raw": 2685031168,
                        "fmt": "2.685B",
                        "longFmt": "2,685,031,168",
                    },
                    "fiftyTwoWeekLow": {"raw": 1.7, "fmt": "1.70"},
                    "fiftyTwoWeekHigh": {"raw": 19.39, "fmt": "19.39"},
                    "regularMarketOpen": {"raw": 9.4584, "fmt": "9.46"},
                    "priceHint": 2,
                },
                {
                    "symbol": "OMER",
                    "shortName": "Omeros Corporation",
                    "longName": "Omeros Corporation",
                    "quoteType": "EQUITY",
                    "currency": "USD",
                    "regularMarketPrice": {"raw": 19.91, "fmt": "19.91"},
                    "regularMarketChange": {"raw": 0.9699993, "fmt": "0.97"},
                    "regularMarketChangePercent": {"raw": 5.1214323, "fmt": "5.12%"},
                    "regularMarketVolume": {
                        "raw": 695530,
                        "fmt": "695,530",
                        "longFmt": "695,530",
                    },
                    "averageDailyVolume3Month": {
                        "raw": 775257,
                        "fmt": "775,257",
                        "longFmt": "775,257",
                    },
                    "marketCap": {
                        "raw": 1233101952,
                        "fmt": "1.233B",
                        "longFmt": "1,233,101,952",
                    },
                    "fiftyTwoWeekLow": {"raw": 9.25, "fmt": "9.25"},
                    "fiftyTwoWeekHigh": {"raw": 25.46, "fmt": "25.46"},
                    "regularMarketOpen": {"raw": 18.93, "fmt": "18.93"},
                    "priceHint": 2,
                },
                {
                    "symbol": "TMBR",
                    "shortName": "Timber Pharmaceuticals, Inc.",
                    "longName": "Timber Pharmaceuticals, Inc.",
                    "quoteType": "EQUITY",
                    "currency": "USD",
                    "regularMarketPrice": {"raw": 2.24, "fmt": "2.2400"},
                    "regularMarketChange": {"raw": 0.01999998, "fmt": "0.0200"},
                    "regularMarketChangePercent": {"raw": 0.9009, "fmt": "0.90%"},
                    "regularMarketVolume": {
                        "raw": 3054710,
                        "fmt": "3.055M",
                        "longFmt": "3,054,710",
                    },
                    "averageDailyVolume3Month": {
                        "raw": 11088947,
                        "fmt": "11.089M",
                        "longFmt": "11,088,947",
                    },
                    "marketCap": {
                        "raw": 26541760,
                        "fmt": "26.542M",
                        "longFmt": "26,541,760",
                    },
                    "fiftyTwoWeekLow": {"raw": 0.665, "fmt": "0.6650"},
                    "fiftyTwoWeekHigh": {"raw": 10.44, "fmt": "10.4400"},
                    "regularMarketOpen": {"raw": 2.23, "fmt": "2.2300"},
                    "priceHint": 4,
                },
                {
                    "symbol": "TRHC",
                    "shortName": "Tabula Rasa HealthCare, Inc.",
                    "longName": "Tabula Rasa HealthCare, Inc.",
                    "quoteType": "EQUITY",
                    "currency": "USD",
                    "regularMarketPrice": {"raw": 44.51, "fmt": "44.51"},
                    "regularMarketChange": {"raw": 0.11999893, "fmt": "0.12"},
                    "regularMarketChangePercent": {"raw": 0.27032876, "fmt": "0.27%"},
                    "regularMarketVolume": {
                        "raw": 678554,
                        "fmt": "678,554",
                        "longFmt": "678,554",
                    },
                    "averageDailyVolume3Month": {
                        "raw": 474606,
                        "fmt": "474,606",
                        "longFmt": "474,606",
                    },
                    "marketCap": {
                        "raw": 1098617984,
                        "fmt": "1.099B",
                        "longFmt": "1,098,617,984",
                    },
                    "fiftyTwoWeekLow": {"raw": 30.12, "fmt": "30.12"},
                    "fiftyTwoWeekHigh": {"raw": 69.31, "fmt": "69.31"},
                    "regularMarketOpen": {"raw": 44.33, "fmt": "44.33"},
                    "priceHint": 2,
                },
                {
                    "symbol": "BGS",
                    "shortName": "B&G Foods, Inc. B&G Foods, Inc.",
                    "longName": "B&G Foods, Inc.",
                    "quoteType": "EQUITY",
                    "currency": "USD",
                    "regularMarketPrice": {"raw": 33.06, "fmt": "33.06"},
                    "regularMarketChange": {"raw": 1.3400021, "fmt": "1.34"},
                    "regularMarketChangePercent": {"raw": 4.2244706, "fmt": "4.22%"},
                    "regularMarketVolume": {
                        "raw": 2256120,
                        "fmt": "2.256M",
                        "longFmt": "2,256,120",
                    },
                    "averageDailyVolume3Month": {
                        "raw": 2242804,
                        "fmt": "2.243M",
                        "longFmt": "2,242,804",
                    },
                    "marketCap": {
                        "raw": 2139778816,
                        "fmt": "2.14B",
                        "longFmt": "2,139,778,816",
                    },
                    "trailingPE": {"raw": 16.205883, "fmt": "16.21"},
                    "fiftyTwoWeekLow": {"raw": 15.65, "fmt": "15.65"},
                    "fiftyTwoWeekHigh": {"raw": 47.84, "fmt": "47.84"},
                    "regularMarketOpen": {"raw": 31.89, "fmt": "31.89"},
                    "priceHint": 2,
                },
            ],
            "columns": [
                {"data": "symbol"},
                {"data": "shortName"},
                {"data": "longName"},
                {"data": "quoteType"},
                {"data": "currency"},
                {"data": "currencyCode"},
                {"data": "underlyingSymbol"},
                {"data": "regularMarketPrice"},
                {"data": "regularMarketChange"},
                {"data": "regularMarketChangePercent"},
                {"data": "regularMarketVolume"},
                {"data": "averageDailyVolume3Month"},
                {"data": "marketCap"},
                {"data": "trailingPE"},
                {"data": "fiftyTwoWeekLow"},
                {"data": "fiftyTwoWeekHigh"},
                {"data": "regularMarketOpen"},
            ],
            "total": 4422,
            "filters": {},
        },
    },
    "_screeners": {
        "url": "/screener",
        "response": {
            "screeners": [
                {
                    "title": "Fair Value Screener",
                    "predefinedScr": True,
                    "description": "Undervalued stocks with a strong & consistent "
                    "history of earnings and revenue growth, sorted "
                    "by rate of return",
                    "canonicalName": "FAIR_VALUE_SCREENER",
                },
                {
                    "title": "Most Shorted Stocks",
                    "predefinedScr": True,
                    "description": "Stocks with the highest short interest positions "
                    "from Nasdaq and NYSE reports released every two "
                    "weeks.",
                    "canonicalName": "MOST_SHORTED_STOCKS",
                },
                {
                    "title": "Undervalued Growth Stocks",
                    "predefinedScr": True,
                    "description": "Stocks with earnings growth rates better than 25% "
                    "and relatively low PE and PEG ratios.",
                    "canonicalName": "UNDERVALUED_GROWTH_STOCKS",
                },
                {
                    "title": "Growth Technology Stocks",
                    "predefinedScr": True,
                    "description": "Technology stocks with revenue and earnings growth "
                    "in excess of 25%.",
                    "canonicalName": "GROWTH_TECHNOLOGY_STOCKS",
                },
                {
                    "title": "Day Gainers - US",
                    "predefinedScr": True,
                    "description": "Stocks ordered in descending order by price percent "
                    "change greater than 3% with respect to the previous "
                    "close",
                    "canonicalName": "DAY_GAINERS",
                },
                {
                    "title": "Day Losers - US",
                    "predefinedScr": True,
                    "description": "Stocks ordered in ascending order by price percent "
                    "change with respect to the previous close",
                    "canonicalName": "DAY_LOSERS",
                },
                {
                    "title": "Most Actives - US",
                    "predefinedScr": True,
                    "description": "Stocks ordered in descending order by intraday "
                    "trade volume",
                    "canonicalName": "MOST_ACTIVES",
                },
                {
                    "title": "Potentially undervalued large cap stocks",
                    "predefinedScr": True,
                    "description": "Large cap stocks that are potentially undervalued, "
                    "ordered descending by volume",
                    "canonicalName": "UNDERVALUED_LARGE_CAPS",
                },
                {
                    "title": "Aggresive small cap stocks",
                    "predefinedScr": True,
                    "description": "Small cap stocks with high earnings growth rates",
                    "canonicalName": "AGGRESSIVE_SMALL_CAPS",
                },
                {
                    "title": "Small caps with momentum",
                    "predefinedScr": True,
                    "description": "Small cap stocks with percentchange greater than 5%",
                    "canonicalName": "SMALL_CAP_GAINERS",
                },
                {
                    "title": "Top Mutual Funds",
                    "predefinedScr": True,
                    "description": "Funds with Performance Rating of 4 & 5 ordered by "
                    "Percent Change",
                    "canonicalName": "TOP_MUTUAL_FUNDS",
                },
                {
                    "title": "Portfolio Anchors",
                    "predefinedScr": True,
                    "description": "Funds with Performance Rating of 4 & 5 and top-half "
                    "returns that could serve as a rock-solid core of an "
                    "investor&#39;s portfolio",
                    "canonicalName": "PORTFOLIO_ANCHORS",
                },
                {
                    "title": "Solid Large Growth Funds",
                    "predefinedScr": True,
                    "description": "Large Growth Funds with Performance Rating of 4 & 5 "
                    "and top-half returns",
                    "canonicalName": "SOLID_LARGE_GROWTH_FUNDS",
                },
                {
                    "title": "Solid Mid-Cap Growth Funds",
                    "predefinedScr": True,
                    "description": "Mid-Cap Growth Funds with Performance Rating of 4 & "
                    "5 and top-half returns",
                    "canonicalName": "SOLID_MIDCAP_GROWTH_FUNDS",
                },
                {
                    "title": "Conservative Foreign Funds",
                    "predefinedScr": True,
                    "description": "Foreign funds with Performance Rating of 4 & 5, "
                    "low risk and top-half returns",
                    "canonicalName": "CONSERVATIVE_FOREIGN_FUNDS",
                },
                {
                    "title": "High Yield Bond",
                    "predefinedScr": True,
                    "description": "High Yield Bond with Performance Rating of 4 & 5, "
                    "low risk and top-half returns",
                    "canonicalName": "HIGH_YIELD_BOND",
                },
            ]
        },
    },
}
